# permissions for end users to view servicecatalogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicecatalog-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: servicecatalog-viewer-role
rules:
- apiGroups:
  - core.launchboxhq.io
  resources:
  - servicecatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.launchboxhq.io
  resources:
  - servicecatalogs/status
  verbs:
  - get
