# permissions for end users to edit spaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: space-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: space-editor-role
rules:
- apiGroups:
  - core.launchboxhq.io
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.launchboxhq.io
  resources:
  - spaces/status
  verbs:
  - get
