{{- if .Values.agent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-agent
rules:
  - apiGroups:
      - core.launchboxhq.io
    resources:
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.launchboxhq.io
    resources:
      - projects/status
    verbs:
      - get
  - apiGroups:
      - pkg.crossplane.io
    resources:
      - configurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
