{{- if and .Values.serviceAccount.create .Values.agent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.serviceAccountName" . }}-agent
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    launchboxhq.io/component: agent
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
