{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}-agent
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    launchboxhq.io/component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
      launchboxhq.io/component: agent
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
        launchboxhq.io/component: agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}-agent
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # TODO: The OIDC configurations should be sourced from environment variables
          args:
            - agent
            - --stream-url={{ .Values.agent.streamUrl }}
            - --client-id={{ .Values.agent.clientId }}
            - --client-secret={{ .Values.agent.clientSecret }}
            - --token-url={{ .Values.agent.tokenUrl }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: 8081
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /readyz
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
