apiVersion: core.launchboxhq.io/v1alpha1
kind: ServiceCatalog
metadata:
  labels:
    app.kubernetes.io/name: servicecatalog
    app.kubernetes.io/instance: servicecatalog-sample
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app
  name: servicecatalog-sample
spec:
  # TODO(user): Add fields here
