name: Helm

on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  publish:
    name: Push Chart
    runs-on: ubuntu-22.04
    env:
      GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/operator
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.3
      - run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin
      - run: helm chart save ${{ github.workspace }}/deploy/charts/operator ${{ env.GCR_IMAGE }}:${{ github.sha }}
      - run: helm chart push ${{ env.GCR_IMAGE }}-chart:${{ github.sha }}
