name: Helm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
      - name: Get Chart version
        id: chart_version
        run: |
          version=$(yq r 'deploy/charts/operator/Chart.yaml' .version)
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: agent
          repository: launchboxio/operator/helm
          tag: ${{ steps.chart_version.outputs.version }}
          path: deploy/charts/operator
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false
