name: Helm

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Push Chart
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.3
      - uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: operator
          repository: launchboxhqio
          tag: ${{github.ref_name}}
          path: deploy/charts/operator # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false


