#name: Helm
#
#on:
#  push:
#    branches:
#      - main
##    paths:
##      - deploy/charts/operator/Chart.yaml
#
#jobs:
#  call-update-helm-repo:
#    uses: launchboxio/helm-charts/.github/workflows/update-helm-repo.yaml@main
#    with:
#      charts_dir: deploy/charts
#      cr_configfile: deploy/charts/cr.yaml
#      ct_configfile: deploy/charts/ct.yaml
#      helm_tag_prefix: helm
#    secrets:
#      helm_repo_token: ${{ secrets.HELM_CHARTS_ACCESS_TOKEN }}
